import type { Metadata } from "next";

import "./globals.css";
import "./globals.scss";
import "../styles/legacy.clean.css";
import { MockGeneralConfig } from "@/MockData/fake-data";
import { QueryProvider } from "@/providers";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const smallPageIcon = MockGeneralConfig.smallPageIcon;

  return (
    <html lang="en">
      <head>
        <link rel="icon" href={smallPageIcon?.asset._ref} sizes="any" />
        <style
          precedence="default"
          href="theme-colors"
          dangerouslySetInnerHTML={{
            __html: `:root {
              --hover-color: ${MockGeneralConfig.hoverColor};
              --active-color: ${MockGeneralConfig.activeColor};
              --details-background-color: ${MockGeneralConfig.detailsBackgroundColor};
            }`,
          }}
        />
      </head>
      <body
        id="body"
      >
        <QueryProvider>
          <div id="container">
            <div id="container">{children}</div>
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
