import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./globals.scss";
import "../styles/legacy.clean.css";
import {MockGeneralConfig} from "../MockData/fake_data"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const smallPageIcon = MockGeneralConfig.smallPageIcon;

  return (
    <html lang="en" className=" js no-flexbox canvas canvastext webgl no-touch geolocation postmessage no-websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths">
      <head>
        <link rel="icon" href={smallPageIcon.asset._ref} sizes="any" />
        <style
          precedence="default"
          href="theme-colors"
          dangerouslySetInnerHTML={{
            __html: `:root {
              --hover-color: ${MockGeneralConfig.hoverColor};
              --active-color: ${MockGeneralConfig.activeColor};
              --details-background-color: ${MockGeneralConfig.detailsBackgroundColor};
            }`
          }}
        />
      </head>
      <body
        id="body"
      >
        {children}
      </body>
    </html>
  );
}
